In [1]:
with open('wiki_edit.txt','r') as f:
    column_names = f.readline().strip().split(',')
    data = []
    for line in f:
        data.append(line.strip().split(','))

In [2]:
column_names[:5]

['9019643 Anarchism 2005-01-01 ip:24.136.172.37']

In [3]:
import pandas as p
name = ['Revisionld','Articled','Timestamp','Editor']
data = p.read_table('wiki_edit.txt',sep=' ',header=None,names=name)

In [4]:
data

       Revisionld                Articled   Timestamp              Editor
0         9019643               Anarchism  2005-01-01    ip:24.136.172.37
1         9062018               Anarchism  2005-01-03     ip:137.53.22.23
2         9085524               Anarchism  2005-01-03     ip:24.42.90.254
3         9140836               Anarchism  2005-01-06    ip:69.61.184.201
4         9160986                       A  2005-01-06                 Fvw
5         9243125                Achilles  2005-01-08       ip:24.3.52.22
6         9034734         Abraham_Lincoln  2005-01-02       ip:24.85.3.38
7         9082287         Abraham_Lincoln  2005-01-03            Polynova
8         9085580         Abraham_Lincoln  2005-01-03  ip:128.143.193.134
9         9090610         Abraham_Lincoln  2005-01-04              JimWae
10        9090968         Abraham_Lincoln  2005-01-04              JimWae
11        9134428         Abraham_Lincoln  2005-01-05              JimWae
12        9165313         Abraham_Lincoln  2005-01-06              JimWae
13        9167237         Abraham_Lincoln  2005-01-07              JimWae
14        9261586         Abraham_Lincoln  2005-01-10     ip:64.5.154.156
15        9288161         Abraham_Lincoln  2005-01-11      ip:207.72.66.5
16        9288252         Abraham_Lincoln  2005-01-11      ip:207.72.66.5
17        9072606           Academy_Award  2005-01-02   ip:67.182.173.144
18        9344330                Altruism  2005-01-13      Paul_Stansifer
19        9365136                Altruism  2005-01-14       AdamRetchless
20        9365499                Altruism  2005-01-14                RJII
21        9366392                Altruism  2005-01-14                RJII
22        9208696                Ayn_Rand  2005-01-08    ip:70.68.228.208
23        9194806                 Algeria  2005-01-05   ip:194.228.128.63
24        9249680                 Algeria  2005-01-10        Gzornenplatz
25        9301374                 Algeria  2005-01-11        Gznorneplatz
26        9004293                 Alchemy  2005-01-01         Jdforrester
27        9015217                 Alchemy  2005-01-01              Wereon
28        9015731                 Alchemy  2005-01-01       House_of_Shin
29        9016874                 Alchemy  2005-01-01           Xerxes314
...           ...                     ...         ...                 ...
28179     9264476      Abrahamic_religion  2005-01-10           Ramospaul
28180     9264567      Abrahamic_religion  2005-01-10               Jayjg
28181     9264631      Abrahamic_religion  2005-01-10               Jayjg
28182     9264657      Abrahamic_religion  2005-01-10           Ramospaul
28183     9312060      Abrahamic_religion  2005-01-12    ip:212.137.57.25
28184     9326382      Abrahamic_religion  2005-01-13     ip:68.229.88.70
28185     9326892      Abrahamic_religion  2005-01-13     ip:68.229.88.70
28186    10062218                Buttocks  2005-01-09            Guanabot
28187     9204452      List_of_occultists  2005-01-05    ip:139.149.1.194
28188     9185598        Unseen_character  2005-01-07    ip:80.42.130.150
28189     9210396        Unseen_character  2005-01-07    ip:80.42.130.150
28190     9237176        Unseen_character  2005-01-09   ip:128.82.252.157
28191     9105244  Multiverse_(DC_Comics)  2005-01-04            JonMoore
28192     9215105  Multiverse_(DC_Comics)  2005-01-04      TANK_Ex_Mortis
28193     9586111                   Iksar  2005-01-01      ip:67.161.63.6
28194     9192837               Dreadstar  2005-01-08           Kazvorpal
28195     9053314               Gay_pride  2005-01-01          CanisRufus
28196     9077223              Sodomy_law  2005-01-03   ip:208.186.187.81
28197     9077273              Sodomy_law  2005-01-03   ip:208.186.187.81
28198     9172689               Zoophilia  2005-01-07                 FT2
28199     9175674               Zoophilia  2005-01-07                 FT2
28200     9187135               Zoophilia  2005-01-07      ip:82.35.40.33
28201     9476562               Zoophilia  2005-01-10                 FT2
28202     9022032               Main_Page  2005-01-01                Tom-
28203     9041310               Main_Page  2005-01-02           Dbachmann
28204     9062582                    Mars  2005-01-03   ip:12.202.207.180
28205     9336173                    Mars  2005-01-10               Matey
28206     9581631        Brentwood,_Essex  2005-01-10              Cleduc
28207     9005140         Michael_Jackson  2005-01-01     ip:24.25.215.70
28208     9346122         Michael_Jackson  2005-01-13   ip:24.205.118.227

[28209 rows x 4 columns]

In [5]:
data[:3]

   Revisionld   Articled   Timestamp            Editor
0     9019643  Anarchism  2005-01-01  ip:24.136.172.37
1     9062018  Anarchism  2005-01-03   ip:137.53.22.23
2     9085524  Anarchism  2005-01-03   ip:24.42.90.254

In [6]:
data.shape

(28209, 4)

In [8]:
counts = data['Articled'].value_counts()

In [9]:
top_article = data['Articled'].value_counts()
top_article[:5]

2004_Indian_Ocean_earthquake                                 186
Humanitarian_response_to_the_2004_Indian_Ocean_earthquake     84
Tsunami                                                       64
Donations_for_victims_of_the_2004_Indian_Ocean_earthquake     55
January_2005                                                  54
Name: Articled, dtype: int64

In [10]:
top_editor = data['Editor'].value_counts()
top_editor[:5]

CanisRufus       241
Jerryseinfeld    224
SimonP           209
Pcpcpc           206
Grutness         175
Name: Editor, dtype: int64

In [11]:
import json
f = open('wh.json')
tweets = [json.loads(line) for line in f]
f.close()

In [12]:
from collections import defaultdict

counts = defaultdict(int)
for tweet in tweets:
    words = tweet['text'].split(' ')
    for word in words:
        counts[word] += 1

In [13]:
import operator

In [14]:
sorted_words = sorted(counts.items(), key=operator.itemgetter(1))
sorted_words[-15:]

[('my', 7),
 ('@WhiteHouse:', 8),
 ('you', 8),
 ('for', 8),
 ('a', 9),
 ('@vj44:', 9),
 ('in', 9),
 ('that', 9),
 ('@POTUS', 9),
 ('and', 9),
 ('our', 10),
 ('of', 22),
 ('to', 27),
 ('the', 28),
 ('RT', 34)]